{% set name = "dsm2dtm" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be2368e13abbb3a6397e4040369c64e6e3ed88f3694e3d9b431dc7be082ecf71

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.12
    - pip
    - setuptools >=61.0
  run:
    - python >=3.12
    - numpy
    - rasterio
    - scipy
    - scikit-image
    - pyproj

test:
  imports:
    - dsm2dtm
  commands:
    - pip check
    - dsm2dtm --help
  requires:
    - pip

about:
  home: https://github.com/seedlit/dsm2dtm
  summary: Generate DTM (Digital Terrain Model) from DSM (Digital Surface Model)
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/seedlit/dsm2dtm#readme
  dev_url: https://github.com/seedlit/dsm2dtm

extra:
  recipe-maintainers:
    - seedlit
    - r1j1t