{% set name = "dsm2dtm" %}
{% set version = "0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/seedlit/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 64a08fd43eea5c98cd7b7d4426f7646ad989e607ceb104047348b75d2aa2584b

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv "

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - gdal >=3.0.4
    - rasterio >=1.2.5
    - numpy >=1.20.3
    - certifi

test:
  imports:
    - dsm2dtm
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/seedlit/dsm2dtm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Generates DTM (Digital Terrain Model) from DSM (Digital Surface Model).
  description: |
    Generates DTM (Digital Terrain Model) from DSM (Digital Surface Model).
  doc_url: https://github.com/seedlit/dsm2dtm#readme
  dev_url: https://github.com/seedlit/dsm2dtm
extra:
  recipe-maintainers:
    - seedlit
    - r1j1t
