{% set name = "dsm2dtm" %}
{% set version = "0.3.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f4ef30fb4fc17438ded8da88f560a0cfbdbd47eb94c43bdabc43dff5a86c6932

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0
  run:
    - python >={{ python_min }}
    - numpy
    - rasterio
    - scipy
    - scikit-image
    - pyproj

test:
  imports:
    - dsm2dtm
  commands:
    - pip check
    - dsm2dtm --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/seedlit/dsm2dtm
  summary: Generate DTM (Digital Terrain Model) from DSM (Digital Surface Model)
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/seedlit/dsm2dtm#readme
  dev_url: https://github.com/seedlit/dsm2dtm

extra:
  recipe-maintainers:
    - seedlit
    - r1j1t
